language: scala
sudo: false
dist: xenial
services:
  - mysql
jdk:
- openjdk8
- openjdk11
before_script:
- mysql -e "CREATE DATABASE test;" -uroot
- unset _JAVA_OPTIONS
script:
- sbt scalafmtCheck scalafmtSbtCheck test:scalafmtCheck migrate domain/checkGeneratedCode compile test
