language: scala
sudo: false
jdk:
- oraclejdk8
- openjdk11
before_script:
- mysql -e "CREATE DATABASE test;" -uroot
- unset _JAVA_OPTIONS
script:
- sbt scalafmtCheck scalafmtSbtCheck test:scalafmtCheck migrate domain/checkGeneratedCode compile test
